FROM httpd:2.4

RUN apt-get update && \
    apt-get install -y \
        php8.2 \
        php8.2-cli \
        php8.2-common \
        php8.2-curl \
        php8.2-gd \
        php8.2-json \
        php8.2-mbstring \
        php8.2-mysql \
        php8.2-xml \
        php8.2-zip \
        libapache2-mod-php8.2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN a2enmod php8.2

COPY ./apache /usr/local/apache2/htdocs/

EXPOSE 80
