---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

python_packages:
  - python3-pip
  - python3-setuptools
  - python3-docker
  - python3-requests 